app = "trademark-search"
primary_region = "ord"

[build]
  dockerfile = "Dockerfile"

[env]
  FLASK_ENV = "production"
  HEADLESS = "true"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[http_service.http_options]
  response = "Fly-Request-Id"

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512